name: Convert Metasploitable2 to QCOW2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies (qemu-utils, unzip, wget)
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-utils unzip wget

    - name: Download Metasploitable2 ZIP
      run: |
        
        wget http://downloads.metasploit.com/data/metasploitable/metasploitable-linux-2.0.0.zip
        file metasploitable-linux-2.0.0.zip 
        unzip metasploitable-linux-2.0.0.zip 
        cd Metasploitable2-Linux

    - name: Convert VMDK to QCOW2
      run: |
        mkdir qcow2
        VMDK_FILE=$(find . -name "*.vmdk" | head -n 1)
        qemu-img convert -f vmdk -O qcow2 "$VMDK_FILE" qcow2/metasploitable2.qcow2

    - name: Upload QCOW2 as artifact
      uses: actions/upload-artifact@v4
      with:
        name: metasploitable2-qcow2
        path: qcow2/metasploitable2.qcow2
